controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true #assumes the joints reaches the previous target perfectly. Avoids sudden abort
    allow_integration_in_goal_trajectories: true #automatically estimates velocities & accel to each motion. you only need position and time stamps.
    gains:
      joint_1: {p: 100.0, i: 0.01, d: 10.0}
      joint_2: {p: 100.0, i: 0.01, d: 10.0}
      joint_3: {p: 100.0, i: 0.01, d: 10.0}
      joint_4: {p: 100.0, i: 0.01, d: 10.0}
      joint_5: {p: 100.0, i: 0.01, d: 10.0}

forward_position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    interface_name: position
